### PR TITLE
fix seqan issue link

### PR DESCRIPTION
**Pull request by mr-c**
`author:@me` refers to the logged in user; replacing with a direct link to the issue of @paoloshasta

### CODE REVIEW

**Comment by mr-c** [comment]
image

versus

image
 
:-)

**Comment by paoloshasta** [comment]
I see. However when I tried the same from a private browser window (that is, not logged in to GitHub) I got the opposite result. Is there a way to craft a link that will work correctly whether or not you are logged in to GitHub?

**Comment by mr-c** [comment]
> I see. However when I tried the same from a private browser window (that is, not logged in to GitHub) I got the opposite result. Is there a way to craft a link that will work correctly whether or not you are logged in to GitHub?

I think you may be clicking on the wrong links?

The old link is  https://github.com/seqan/seqan/issues?q=is%3Aissue+author%3A%40me+is%3Aclosed


The new link is https://github.com/seqan/seqan/issues/2524

**Comment by paoloshasta** [comment]
Oops you are right so sorry! I had it reversed.

**Pull request merged**
